name: Build HackWatch Firmware
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Pip/PlatformIO Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Compile Firmware
        run: pio run

      - name: Upload Finished Binaries
        uses: actions/upload-artifact@v4
        with:
          name: hackwatch-v2-binaries
          path: .pio/build/**/*.bin
